name: Deploy TwinBackend

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout workflow repo
              uses: actions/checkout@v3

            - name: SSH to EC2 and deploy
              uses: appleboy/ssh-action@v0.1.9
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USER }}
                  key: ${{ secrets.EC2_SSH_KEY }}
                  script: |
                      #!/bin/bash
                      set -e

                      PROJECT_DIR=~/TwinBackend

                      # Install git if missing
                      if ! command -v git &> /dev/null; then
                        echo "Git not found, installing..."
                        sudo dnf install git -y
                      fi

                      # Check if project exists
                      if [ -d "$PROJECT_DIR" ]; then
                        echo "Project exists, pulling latest changes..."
                        cd "$PROJECT_DIR"
                        git reset --hard
                        git pull origin main
                      else
                        echo "Project does not exist, cloning..."
                        git clone https://github.com/AjayKumar211097/TwinBackend.git "$PROJECT_DIR"
                        cd "$PROJECT_DIR"
                      fi

                      # Install Node.js if missing
                      if ! command -v node &> /dev/null; then
                        echo "Node.js not found, installing..."
                        curl -fsSL https://rpm.nodesource.com/setup_20.x | sudo bash -
                        sudo dnf install -y nodejs
                      fi

                      # Install dependencies
                      cd "$PROJECT_DIR"
                      npm install

                      # Restart app (assumes pm2)
                      if command -v pm2 &> /dev/null; then
                        pm2 restart TwinBackend || pm2 start index.js --name TwinBackend
                      else
                        echo "PM2 not found, installing..."
                        sudo npm install -g pm2
                        pm2 start index.js --name TwinBackend
                      fi

                      echo "Deployment completed!"
