name: Deploy TwinBackend

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout workflow repo
              uses: actions/checkout@v3

            - name: SSH to EC2 and deploy
              uses: appleboy/ssh-action@v0.1.9
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USER }}
                  key: ${{ secrets.EC2_SSH_KEY }}
                  script: |
                      #!/bin/bash
                      set -e

                      PROJECT_DIR=~/TwinBackend

                      # Install git if missing
                      if ! command -v git &> /dev/null; then
                        echo "Git not found, installing..."
                        sudo dnf install git -y
                      fi

                      # Check if project exists
                      if [ -d "$PROJECT_DIR" ]; then
                        echo "Project exists, pulling latest changes..."
                        cd "$PROJECT_DIR"
                        git reset --hard
                        git pull origin main
                      else
                        echo "Project does not exist, cloning..."
                        git clone https://github.com/AjayKumar211097/TwinBackend.git "$PROJECT_DIR"
                        cd "$PROJECT_DIR"
                      fi

                      # Install Node.js if missing
                      if ! command -v node &> /dev/null; then
                        echo "Node.js not found, installing..."
                        curl -fsSL https://rpm.nodesource.com/setup_20.x | sudo bash -
                        sudo dnf install -y nodejs
                      fi

                      # Install dependencies
                      cd "$PROJECT_DIR"
                      sudo npm install


                      # Build TypeScript
                      npx tsc

                      # Install PM2 if missing
                      if ! command -v pm2 &> /dev/null; then
                      echo "PM2 not found, installing..."
                        sudo npm install -g ts-node pm2
                      fi

                      # Start or restart using PM2 with ecosystem.config.ts
                        pm2 start dist/rest/index.js --name TwinBackend-REST || pm2 restart TwinBackend-REST
                        pm2 start dist/ws/index.js --name TwinBackend-WS || pm2 restart TwinBackend-WS

                      # Setup PM2 to start on system boot
                        pm2 startup -u $USER --hp $HOME
                        pm2 save

                      echo "Deployment completed!"
